interface GithubRepository {
    id:string, // 93735461,
    node_id:string, // R_kgDOL09xJQ",
    name:string, // Asteroids",
    full_name:string, // dragonero2704/Asteroids",
    private:boolean, // false,
    owner: { 
      login:string, // dragonero2704",
      id:string, // 0794906,
      node_id:string, // MDQ6VXNlcjYwNzk0OTA2",
      avatar_url:string, // https://avatars.githubusercontent.com/u/60794906?v=4",
      gravatar_id:string, // ",
      url:string, // https://api.github.com/users/dragonero2704",
      html_url:string, // https://github.com/dragonero2704",
      followers_url:string, // https://api.github.com/users/dragonero2704/followers",
      following_url:string, // https://api.github.com/users/dragonero2704/following{/other_user}",
      gists_url:string, // https://api.github.com/users/dragonero2704/gists{/gist_id}",
      starred_url:string, // https://api.github.com/users/dragonero2704/starred{/owner}{/repo}",
      subscriptions_url:string, // https://api.github.com/users/dragonero2704/subscriptions",
      organizations_url:string, // https://api.github.com/users/dragonero2704/orgs",
      repos_url:string, // https://api.github.com/users/dragonero2704/repos",
      events_url:string, // https://api.github.com/users/dragonero2704/events{/privacy}",
      received_events_url:string, // https://api.github.com/users/dragonero2704/received_events",
      type:string, // User",
      user_view_type:string, // public",
      site_admin:boolean, // alse
    },
    html_url:string, // https://github.com/dragonero2704/Asteroids",
    description:string, // Asteroids vintage game with pygame",
    fork:boolean, // alse,
    url:string, // https://api.github.com/repos/dragonero2704/Asteroids",
    forks_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/forks",
    keys_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/keys{/key_id}",
    collaborators_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/collaborators{/collaborator}",
    teams_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/teams",
    hooks_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/hooks",
    issue_events_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/issues/events{/number}",
    events_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/events",
    assignees_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/assignees{/user}",
    branches_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/branches{/branch}",
    tags_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/tags",
    blobs_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/git/blobs{/sha}",
    git_tags_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/git/tags{/sha}",
    git_refs_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/git/refs{/sha}",
    trees_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/git/trees{/sha}",
    statuses_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/statuses/{sha}",
    languages_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/languages",
    stargazers_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/stargazers",
    contributors_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/contributors",
    subscribers_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/subscribers",
    subscription_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/subscription",
    commits_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/commits{/sha}",
    git_commits_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/git/commits{/sha}",
    comments_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/comments{/number}",
    issue_comment_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/issues/comments{/number}",
    contents_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/contents/{+path}",
    compare_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/compare/{base}...{head}",
    merges_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/merges",
    archive_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/{archive_format}{/ref}",
    downloads_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/downloads",
    issues_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/issues{/number}",
    pulls_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/pulls{/number}",
    milestones_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/milestones{/number}",
    notifications_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/notifications{?since,all,participating}",
    labels_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/labels{/name}",
    releases_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/releases{/id}",
    deployments_url:string, // https://api.github.com/repos/dragonero2704/Asteroids/deployments",
    created_at:string, // 2024-04-29T19:12:56Z",
    updated_at:string, // 2024-05-01T21:19:20Z",
    pushed_at:string, // 2024-05-01T21:19:17Z",
    git_url:string, // git://github.com/dragonero2704/Asteroids.git",
    ssh_url:string, // git@github.com:dragonero2704/Asteroids.git",
    clone_url:string, // https://github.com/dragonero2704/Asteroids.git",
    svn_url:string, // https://github.com/dragonero2704/Asteroids",
    homepage?:string, // ull,
    size:number, // ,
    stargazers_count:number, // ,
    watchers_count:number, // ,
    language:string, // Python",
    has_issues:boolean, // true,
    has_projects:boolean, // true,
    has_downloads:boolean, // true,
    has_wiki:boolean, // true,
    has_pages:boolean, // false,
    has_discussions:boolean, // false,
    forks_count:number, // ,
    mirror_url?:string, // null,
    archived:boolean, // false,
    disabled:boolean, // false,
    open_issues_count:number, // ,
    license:{ // 
      key:string, // apache-2.0",
      name:string, // Apache License 2.0",
      spdx_id:string, // Apache-2.0",
      url:string, // https://api.github.com/licenses/apache-2.0",
      node_id:string, // MDc6TGljZW5zZTI="
    },
    allow_forking:boolean, // rue,
    is_template:boolean, // alse,
    web_commit_signoff_required:boolean, // alse,
    topics: [
      "client",
      "client-server",
      "discord",
      "express",
      "expressjs",
      "javascript",
      "server"
    ],
    visibility: "public"|"private",
    forks: number,
    open_issues: number,
    watchers: number,
    default_branch: string
  }

export default async function ListRepos(...props) {
  return new Promise<GithubRepository[]>((res, rej) => {
    // get user public repos list
    const url = "https://api.github.com/users/dragonero2704/repos" as string;
    fetch(url)
      .catch((e) => rej(e))
      .then((response:Response) => response.json())
      //TODO fetch all languages and add them to the repository json under the "languages" field
      .then(json=>res(json as GithubRepository[]));
  });
}
